# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing


exec-once = kdeconnect-indicator &
# exec-once = wayland-pipewire-idle-inhibit &
exec-once = /usr/bin/hyprland-monitor-attached /home/dc/.config/hypr/custom/attached.sh /home/dc/.config/hypr/custom/dettached.sh
# exec-once = wlsunset -S 05:30 -s 20:00 -t 4500 &
