# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
monitor=eDP-1,2560x1600@90,auto,1.333
monitor=DP-2,1920x1080@75,1920x0,1

monitor=,preferred,auto,1,mirror,eDP-1
monitor=HDMI-A-1,1920x1080@60,auto,1
xwayland {
  force_zero_scaling = true
}


plugin {
    hyprsplit {
        num_workspaces = 6
    }

hyprfocus {
        enabled = no
        animate_floating = yes
        animate_workspacechange = no
        focus_animation = shrink
        # Beziers for focus animations
        bezier = bezIn, 0.5,0.0,1.0,0.5
        bezier = bezOut, 0.0,0.5,0.5,1.0
        bezier = overshot, 0.05, 0.9, 0.1, 1.05
        bezier = smoothOut, 0.36, 0, 0.66, -0.56
        bezier = smoothIn, 0.25, 1, 0.5, 1
        bezier = realsmooth, 0.28,0.29,.69,1.08
        # Flash settings
        flash {
            flash_opacity = 0.95
            in_bezier = realsmooth
            in_speed = 0.5
            out_bezier = realsmooth
            out_speed = 3
        }
        # Shrink settings
        shrink {
            shrink_percentage = 0.95
            in_bezier = smoothIn
            in_speed = 1
            out_bezier = smoothOut
            out_speed = 2
        }
    }
}
misc {
    vfr = 1
    vrr = 1
}
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 700
    workspace_swipe_fingers = 3
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
}
decoration {
    rounding = 15

}
input {
    follow_mouse = 1
}
