# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
# windowrule = noblur,^(?!(foot))
windowrulev2 = workspace 6, class:^(YouTube Music)$
windowrulev2 = workspace 5, class:^(vesktop)$
windowrulev2 = workspace 6, class:^(whatsapp-for-linux)$
windowrulev2 = idleinhibit[focus], class:^(vlc) # fix pinentry losing focus
windowrulev2 = size 900 600,center, class:^(foot)$ 
windowrulev2 = size 1200 700,center, class:^(org.gnome.Nautilus)$ 
windowrulev2 = center, class:^(foot)$ 
windowrulev2 = center, class:^(org.gnome.Nautilus)$ 
# windowrulev2 = opacity 0.85 0.8, workspace:1, class:^(foot)$
windowrulev2 = float, class:^(Bitwarden)$
windowrulev2 = float, class:^(org.gnome.Calculator)$




workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1, default:true
workspace = 3, monitor:eDP-1, default:true
workspace = 4, monitor:eDP-1, default:true
workspace = 5, monitor:eDP-1, default:true
workspace = 6, monitor:eDP-1, default:true
