add_newline = false
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[ • ](fg:blue)\
$directory
$character"""

right_format = """
[](fg:mauve)\
$git_branch\
[](fg:blue bg:mauve)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
[](fg:surface0 bg:blue)\
$time\
[ ](fg:surface0)\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true
style = "bg:color_orange fg:color_fg0"

[username]
style_user = "bold bg:blue fg:black"
style_root = "red bold"
format = "[](bold fg:blue)[$user]($style)"
disabled = false
show_always = true


[directory]
home_symbol = "  "
read_only = "  "
style = "bg:yellow fg:black"
truncation_length = 5
truncation_symbol = "••/"
format = '[](bold fg:yellow)[$path ]($style)[](bold fg:yellow)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[git_branch]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol $branch ](fg:mantle bg:mauve)]($style)'


[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:base bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $context) ](fg:#83a598 bg:surface1)]($style)'

[conda]
style = "bg:surface1"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:surface1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:text bg:surface0)]($style)'

[line_break]
disabled = false

[character]
success_symbol = "[ ](bold fg:text) "
error_symbol = "[ 󰅙](bold fg:red) "
disabled = false
